### ISSUE TITLE
ChildProcess

### ISSUE THREAD

**Issue by Genstrum** [Stonley890/mc-console-bot#4]
![image](https://user-images.githubusercontent.com/124862914/226482884-b227e429-b7ba-49a2-a1e9-532c1f34922c.png)

**Comment by Stonley890** [comment]
Hmm... I haven't touched this project in a while. I'll look through it and probably rewrite it.

**Comment by Stonley890** [comment]
Fixed 2d0851990da7abcc4b2ef35b9425f8974a91b436
