### ISSUE TITLE
server start issue

### ISSUE THREAD

**Issue by SirSolis** [Stonley890/mc-console-bot#5]
I'm getting a error whenever I try to start the server

https://imgur.com/a/QYUasbh

**Comment by Stonley890** [comment]
I can't seem to reproduce the behavior, but I've pushed a new commit with a potential fix. Try the new [mc-console-bot.py](https://github.com/Stonley890/mc-console-bot/raw/main/mc-console-bot.py) and let me know what happens.

**Comment by Stonley890** [comment]
Resolved.
