### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ChiefBodo7** [Stonley890/mc-console-bot#7]
**Describe the bug**
When I put $startserver in Discord for the bot it send back a message saying:

'An error occurred while starting the server: [Errno 13] Permission denied: '/home/jake/Minecraft-MCServer/run.bat''

There is no error displayed on the bot window just in Discord

What is requiring the permissions? 

Probably a v simple fix am just stuupeed haha

**To Reproduce**

**Expected behavior**
The server to start

**Screenshots**
If applicable, add screenshots to help explain your problem. Remember to remove or obfuscate your Discord Bot Token.

**Environment (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by ChiefBodo7** [comment]
So I should have mentioned that I can start the MC Server using both .bat and .sh on here normally (tried both for the bot as well) but it just returns that error in discord

**Comment by Stonley890** [comment]
Your file may not be marked as executable. Try this command to make it executable:
```
chmod +x path/to/start.sh
```

**Comment by ChiefBodo7** [comment]
I have just done that and I am getting the same output 

Weird as I can start the server anyway and it runs as normal it just doesn't want to start with the bot

**Comment by Stonley890** [comment]
This may not be a permission issue, actually.
Try relocating the `mc-console-bot.py` script inside your `Minecraft-MCServer` folder and setting the variable locally.
```python
MINECRAFT_SERVER_PATH = './run.bat'
```

**Comment by ChiefBodo7** [comment]
We have encountered the same issue unfortunately

**Comment by ChiefBodo7** [comment]
> This may not be a permission issue, actually. Try relocating the `mc-console-bot.py` script inside your `Minecraft-MCServer` folder and setting the variable locally.
> 
> ```python
> MINECRAFT_SERVER_PATH = './run.bat'
> ```

The above fixed my issue but usign the .sh start instead onf the .bat
