### ISSUE TITLE
Minecraft Forge Server starts in the same window as the Script is started in.

### ISSUE THREAD

**Issue by OliDMX** [Stonley890/mc-console-bot#9]
**Describe the bug**
Minecraft Forge Server starts in same window as Script and if server gets shut down, the script doesn't recognize that the server shut down. 

**To Reproduce**
1. Download Forge Server 1.19.2
3. Download some mods
4. start the server via the .bat / .sh, close it again (do not use nogui!)
5. start the configured script, then start the server over discord. 

**Expected behavior**
that the server starts in a seperate CMD and if the server shuts down, it detects the shutdown

**Screenshots**
![image](https://github.com/user-attachments/assets/b395af93-dbb1-4d4f-9e04-7a5f64eb499b)
![image](https://github.com/user-attachments/assets/cf13860e-2854-487f-9718-b55b9795ca9f)

**Environment (please complete the following information):**
 - OS: Windows 11 Proxmox VM
 - Forge 1.19.2 Server
 - Limited in the usr-args to 10GB RAM

**Additional context**

**Comment by Stonley890** [comment]
Could you provide your start script?

**Comment by Stonley890** [comment]
Ah okay no worries.
This seems to be a windows thing so it may or may not be something I can fix but I will try some stuff and see what I can do.

**Comment by Stonley890** [comment]
Okay I think I've found the issue. Your `run.bat` file looks something like this, yes?
```bat
@echo off
REM Forge requires a confirmed set of both JVM and program arguments.
REM Add custom JVM arguments to the user_jvm_args.txt
REM Add custom program arguments {such as nogui} to this file in the next line before the %* of
REM  pass them to this script directly
java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.4.0/win_args.txt &*
pause
```
The `pause` command at the end is what prompts the "Press any key to continue" requirement. Try replacing it with `exit` and see if that solves it.

**Comment by OliDMX** [comment]
soo VM is up again and tried your fix instantly. Works great, now i think after and after why i didn't come up with this solution earlier ;D
Only one small issue is still there, it doesn't tell the discord if the server is up. just when you type in $startserver again. 
If thats not possible with forge or windows things, no problem, i think my friends and me can live without it. 
Otherwise, if there is no big fix for that, you can close this issue! Thanks for your quick help.

**Comment by Stonley890** [comment]
The script is only able to recognize the server if it is spawned using the command. Detecting a server that has started on its own is another process entirely.
Thanks for the report!
